version: "3.7"
services:
  flask-app:
    build: .
    environment:
      DATABASE_URI_PROJECT: mysql+pymysql://root:${PASS}@mysql:3306/${DB_NAME}
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    depends_on:
      database:
        condition: service_healthy
  database:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${PASS}
    ports:
    - target: 3306
      published: 3306
    volumes:
      - type: volume
        source: mysql
        target: /var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h localhost --password=${PASS} 
      timeout: 60s
      retries: 10
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
    depends_on:
    - 'flask-app'
volumes:
  mysql:
